## Homogeneous

똑같은 데이터 타입의 집합

In [15]:
import numpy as np # GPU 지원 안함
import array

In [16]:
a = array.array('i', [1, 2, 3, 4])

In [17]:
a # 빠르다

array('i', [1, 2, 3, 4])

In [18]:
a + a # 시퀀스 데이터 타입이라 수학적 컨셉이 없음
# Operator Overloading 사용해야 함

array('i', [1, 2, 3, 4, 1, 2, 3, 4])

In [19]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

숫자를 다루기 위한 파이썬 라이브러리, 수학적 컨셉, 벡터화

In [12]:
def test_sum(a,b):
  return a + b

In [13]:
test_sum([1,2,3],[4,5,6])

[1, 2, 3, 4, 5, 6]

In [21]:
@np.vectorize
def test_sum(a,b):
  return a + b

In [22]:
test_sum([1,2,3],[4,5,6])

array([5, 7, 9])

# Numpy
- mulit-dimension array(tensor -> linear algebra)
- vectorize(자기 위치의 연산을 별개의 프로세서들이 처리, 동시에 실행할 수 있기 때문에 빠르다, but GPU 지원 안함)
- expert(general)
- [파이토치 예제](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html)

### Data 만들기

In [23]:
import numpy as np
import torch
import tensorflow as tf
import pandas as pd

In [24]:
a = np.array([1,2,3])

In [25]:
type(a)

numpy.ndarray

In [28]:
np.ndarray((2,2))

array([[4.9e-324, 1.5e-323],
       [1.5e-323, 4.9e-324]])

In [30]:
np.zeros((3,3)) # factory function: 값을 만드는 방법

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# __repr__ == __str__

In [35]:
torch.Tensor([1,2,3])

tensor([1., 2., 3.])

In [36]:
print(torch.Tensor([1,2,3]))

tensor([1., 2., 3.])


In [37]:
torch.ones((3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [38]:
tf.constant([1,2,3]) # numpy 값 보여줌

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [39]:
type(tf.constant([1,2,3]))

tensorflow.python.framework.ops.EagerTensor

In [40]:
print(tf.constant([1,2,3])) # numpy 값 안 보여줌

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [41]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

------

In [46]:
a = np.array([[1,1,1,],[1,1,1]])

In [48]:
a.shape

(2, 3)

In [49]:
a.ndim

2

In [50]:
a.dtype

dtype('int64')

In [55]:
a = np.array([[1,1,1,],[1,1,1]], dtype=np.float32)
a.dtype

dtype('float32')

In [56]:
a

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [57]:
tf.constant([[1,1,1,],[1,1,1]], dtype=np.float32)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [59]:
torch.Tensor([[1,1,1,],[1,1,1]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [62]:
torch.zeros((2,3,4), dtype=torch.dtype.is_complex)

TypeError: zeros() received an invalid combination of arguments - got (tuple, dtype=getset_descriptor), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)


In [64]:
tf.ones((2,3,4), dtype=tf.int32)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

In [65]:
np.array([1,2,3.])

array([1., 2., 3.])

In [67]:
torch.Tensor([1,2,3.])

tensor([1., 2., 3.])

In [68]:
tf.constant([1,2,3.])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [69]:
np.array([1,2,'3'])

array(['1', '2', '3'], dtype='<U21')

In [70]:
torch.Tensor([1,2,'3'])

TypeError: must be real number, not str

In [71]:
tf.constant([1,2,'3'])

ValueError: Can't convert Python sequence with mixed types to Tensor.

In [72]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

### Data 연산하기

In [77]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [86]:
x = tf.keras.datasets.mnist.load_data() # 영상
x # numpy data

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [88]:
len(x)

2

In [89]:
(a,b),(c,d) = x

In [90]:
a

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [91]:
a.shape

(60000, 28, 28)

In [98]:
x = tf.keras.datasets.imdb.load_data() # 자연어


In [99]:
x # list(길이가 다름)

((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [100]:
len(x)

2

In [101]:
(a,b),(c,d) = x

In [102]:
a

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [103]:
a.shape

(25000,)

### 5가지

In [104]:
a = np.arange(24).reshape(4,6)

In [105]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [109]:
a[1][1]

np.int64(7)

In [111]:
# 1. Comma indexing
# 인덱싱과 슬라이싱이 동시에
a[1,1:]

array([ 7,  8,  9, 10, 11])

In [117]:
# 2. Boolean Indexing
# 모양을 맞춰
a>3

array([[False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [118]:
a[a>7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [119]:
# 3. Fancy Indexing
# 데이터의 차원을 유지하면서 슬라이싱이 가능
# 내 마음대로 재구성도 가능
a[[1,2]]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [120]:
import seaborn as sns
tips = sns.load_dataset('tips')
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [121]:
tips[['total_bill', 'tip']]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [124]:
# 4. Fancy Indexing의 확장
# 각각 앞은 행, 뒤는 열(1,3)(1,2)를 뽑는다
a[[1,1],[3,2]]

array([9, 8])

In [123]:
# 5. [...]
a[...]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [125]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [127]:
a[0,1,1] # 5

np.int64(5)

In [143]:
a[0,1, :] # 4, 5, 6, 7 (1차원)

array([4, 5, 6, 7])

In [144]:
a[:,0,0] # 0, 12 (1차원)

array([ 0, 12])

In [151]:
a[:,1:2,1:3] # 5, 6, 17, 18 (3차원)

array([[[ 5,  6]],

       [[17, 18]]])

In [153]:
a[:,1:2,1:3].shape # 차원 유지(셋 다 범위)

(2, 1, 2)

In [134]:
a[1,1,::2] # 16, 18

array([16, 18])

In [135]:
a[1, -2:, :-2] # 16, 17, 20, 21 (2차원)

array([[16, 17],
       [20, 21]])

In [141]:
a[0, 1:3, 2:] # 6, 7, 10, 11 (2차원)

array([[ 6,  7],
       [10, 11]])

In [159]:
a = np.arange(6).reshape(2,3,1)

In [160]:
a # 차원 축소 가능, reduce

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [161]:
a.shape

(2, 3, 1)

In [170]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [167]:
a.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [168]:
a.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [169]:
a.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])