In [2]:
... # 생략

Ellipsis

In [4]:
def x():
  ... #pass

In [5]:
import numpy as np

In [7]:
a = np.arange(24) # range

In [8]:
a = np.arange(24).reshape(2,3,4) # reshape
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
a[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a[0,:] # 가장 뒤에 있는 :은 생략 가능

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
a[0,...] # 1개 이상의 :은 ...으로 압축 가능

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a[None]

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]])

In [15]:
b = np.arange(5)

In [16]:
b

array([0, 1, 2, 3, 4])

In [17]:
b[None] # 차원 확대

array([[0, 1, 2, 3, 4]])

In [18]:
b[None,:] # 뒤에 :은 생략 가능

array([[0, 1, 2, 3, 4]])

In [19]:
b[None,...]

array([[0, 1, 2, 3, 4]])

In [21]:
b[None,...].shape

(1, 5)

In [20]:
# None의 위치에 따라서 차원을 늘리는 방향을 바꿀 수 있다.
b[:, None]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [22]:
b[:, None].shape

(5, 1)

In [23]:
c = np.arange(24).reshape(4,6)

In [24]:
c[None]

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [25]:
c[None].shape

(1, 4, 6)

In [26]:
c[:,None,:]

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23]]])

In [27]:
c[:,None,:].shape

(4, 1, 6)

In [28]:
c[:,:,None].shape

(4, 6, 1)

In [29]:
c[...,None].shape

(4, 6, 1)

In [31]:
np.newaxis is None

True

In [32]:
c[...,np.newaxis].shape # 명시적으로 표현

(4, 6, 1)

tensorflow는 3차원 이상의 데이터를 입력받을 수 있다. 2차원 데이터의 경우, `tf.newaxis`를 이용해 차원을 확장시켜준다.



In [33]:
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [34]:
print(c.T) # Transpose

[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [35]:
import tensorflow as tf

In [36]:
x = tf.range(10)
x[..., tf.newaxis]

<tf.Tensor: shape=(10, 1), dtype=int32, numpy=
array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]], dtype=int32)>

NumPy와 tf.Tensor의 가장 확연한 차이
- Tensor는 TPU, GPU 등 가속기메모리 사용 가능
- Tensor는 immutable(불변성)

In [37]:
x # numpy 호환 가능

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [38]:
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [40]:
dir(x) # __array__가 나오므로 numpy 호환된다.

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__tf_tensor__',
 '__tf_tra

In [41]:
aa = np.array([1,2,3])
bb = tf.constant([1,2,3])

In [43]:
tf.add(aa,aa) # tf에 numpy 집어넣을 수 있다, array->tensor

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 4, 6])>

In [44]:
# tensor->numpy, tf 내에서 numpy를 지원, 변환이 빠름(리소스 낭비도 거의 없음)
# tensorflow는 dl/nn을 위한 것, numpy는 범용적임
np.add(bb,bb)

array([2, 4, 6], dtype=int32)

### From, As

**파이썬의 As**
- with 구문
- try except 구문
- import한 패키지 명명

In [45]:
with open('a.txt', 'w') as f:
  print(f)

<_io.TextIOWrapper name='a.txt' mode='w' encoding='UTF-8'>


In [46]:
f = open('a.txt', 'w')

In [48]:
try:
  1/0
except Exception as e:
  print(e)

division by zero


In [ ]:
import numpy as np

파이썬의 From... 이전에 import에 대해

import: 기존에 작업해 둔 것을 가져오는 것.
- import sun

이름이 같으면 뒤엎는다. 이름의 충돌을 막기 위해 별칭을 사용할 수 있다.
- import sun as s

파일을 찾는 규칙
- sys.path 순서대로 찾는다. 여러 개가 있으면 가장 앞에 있는 것 가져온다.



In [49]:
help('from')

The "import" statement
**********************

   import_stmt     ::= "import" module ["as" identifier] ("," module ["as" identifier])*
                   | "from" relative_module "import" identifier ["as" identifier]
                   ("," identifier ["as" identifier])*
                   | "from" relative_module "import" "(" identifier ["as" identifier]
                   ("," identifier ["as" identifier])* [","] ")"
                   | "from" relative_module "import" "*"
   module          ::= (identifier ".")* identifier
   relative_module ::= "."* module | "."+

The basic import statement (no "from" clause) is executed in two
steps:

1. find a module, loading and initializing it if necessary

2. define a name or names in the local namespace for the scope where
   the "import" statement occurs.

When the statement contains multiple clauses (separated by commas) the
two steps are carried out separately for each clause, just as though
the clauses had been separated out into individ

다음을 `sun.py`로 저장한 후 가져오는 방법

```python
a = 1
_a = 2

def x():
  print("x")
  
def _x():
  print("_x")
```

다음과 같이 sun과 sun 내부의 함수 x를 가져올 수 있다.

```python
import sun
import sun as s
from sun import x # 내부의 일부 함수만 가져올 수 있다.
```

'*'는 모든 것을 뜻한다.
 > 삶, 우주, 그리고 모든 것에 대한 궁극적인 질문에 대한 해답. = 42(0101010)
 - 은하수를 여행하는 히치하이커를 위한 안내서, 더글러스 애덤스

```python
from sun import * # *는 전체
```

```python
__all__ = ['x']
```
로 지정해 *를 import하면 x만 import 가능하다.


In [52]:
x = 3

def x():
  yield 1
  yield 2

In [53]:
def x():
  yield from [1,2,3]

In [54]:
raise ZeroDivisionError from Exception # 일종의 경고

ZeroDivisionError: 

**파이썬의 From**
- import 구문
- raise 구문

## Method from, as

In [55]:
import numpy as np

In [57]:
# 데이터 생성할 때 많이 사용
np.fromiter([1,2,3], np.int32)

array([1, 2, 3], dtype=int32)

In [58]:
import pandas as pd

In [ ]:
pd.DataFrame.from_dict # 데이터 생성할 때 많이 사용

In [60]:
import torch

In [61]:
a = torch.tensor([1,2,3])
dir(a)

['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__red

In [67]:
a

tensor([1, 2, 3])

In [63]:
a.numpy()

array([1, 2, 3])

In [64]:
import seaborn as sns

In [65]:
tips = sns.load_dataset('tips')

In [66]:
tips.to_numpy()

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [68]:
tf.data.Dataset.from_tensors # 다른 구조체에서 변화시킬 수 있다.

<function tensorflow.python.data.ops.dataset_ops.DatasetV2.from_tensors(tensors, name=None) -> 'DatasetV2'>

In [74]:
import numpy as np

In [75]:
a = np.array([1,2,3])

In [83]:
np.asarray(a)

array([1, 2, 3])

c : type conversion

python은 명시적인 type conversion이 없음 (새로 만들어야 함)

coerce(type conversion)

In [84]:
a = '문근영'
b = list(a)

In [85]:
b

['문', '근', '영']

In [86]:
3.5+3

6.5

tensorflow: Immutable

pytorch, numpy: Mutable

## Like

데이터 타입과 모양이 같다

In [92]:
a = np.arange(24).reshape(2,3,4)

In [93]:
np.zeros_like(a)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [94]:
np.ones_like(a)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [97]:
a = np.arange(4).reshape(2,2)
a += 1

In [104]:
b = a.copy()

In [98]:
a

array([[1, 2],
       [3, 4]])

In [105]:
a + b

array([[2, 4],
       [6, 8]])

In [106]:
np.add(a,b)

array([[2, 4],
       [6, 8]])

In [107]:
a.__add__(b)

array([[2, 4],
       [6, 8]])

In [108]:
np.subtract(a,b)

array([[0, 0],
       [0, 0]])

In [109]:
np.multiply(a,b) # 각 항마다 곱셈

array([[ 1,  4],
       [ 9, 16]])

In [110]:
a.dot(b) # dot product(inner product)

array([[ 7, 10],
       [15, 22]])

In [111]:
a@b # dot product

array([[ 7, 10],
       [15, 22]])

In [112]:
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])

In [113]:
aa = np.array([1,2,3])
bb = aa.copy()

In [116]:
np.dot(aa,bb) # function

np.int64(14)

In [117]:
aa.dot(bb) # method

np.int64(14)

In [118]:
a = np.arange(4).reshape(2,2)
a += 1

In [121]:
a + 1 # broadcast
# [1 2] + [1 1]
# [3 4]   [1 1]

array([[1, 2],
       [3, 4]])

In [120]:
a = np.arange(4).reshape(2,2)
b = np.arange(3)
a + b

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [126]:
b = np.arange(2).reshape(1,2)
b+=1
b

array([[1, 2]])

In [127]:
a = np.arange(4).reshape(2,2)
a+=1
a

array([[1, 2],
       [3, 4]])

In [128]:
a + b
# b = [1 2]
#     [1 2]

array([[2, 4],
       [4, 6]])

In [131]:
np.info(np.cumsum)

Return the cumulative sum of the elements along a given axis.

Parameters
----------
a : array_like
    Input array.
axis : int, optional
    Axis along which the cumulative sum is computed. The default
    (None) is to compute the cumsum over the flattened array.
dtype : dtype, optional
    Type of the returned array and of the accumulator in which the
    elements are summed.  If `dtype` is not specified, it defaults
    to the dtype of `a`, unless `a` has an integer dtype with a
    precision less than that of the default platform integer.  In
    that case, the default platform integer is used.
out : ndarray, optional
    Alternative output array in which to place the result. It must
    have the same shape and buffer length as the expected output
    but the type will be cast if necessary. See :ref:`ufuncs-output-type`
    for more details.

Returns
-------
cumsum_along_axis : ndarray.
    A new array holding the result is returned unless `out` is
    specified, in which case a re

In [133]:
np.add(1,3)

np.int64(4)

In [135]:
np.add([1,2],[3,4])

array([4, 6])