## Concatenate

In [1]:
import numpy as np

a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [2]:
np.concatenate([a, a])

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [3]:
aa = np.arange(6).reshape(2,3)
aa

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
np.concatenate([aa, aa])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [5]:
np.concatenate([aa, aa], axis=1) # reduction 없음, 2차원 데이터일 때 다르게 작동한다.

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [6]:
import pandas as pd
import seaborn as sns

tips = sns.load_dataset('tips')

tips0 = tips.iloc[0:4]
tips1 = tips.iloc[4:10]

tips0

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2

In [7]:
pd.concat([tips0, tips1])

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [8]:
pd.concat([tips0, tips1], axis=1)

total_bill   tip     sex smoker  day    time  size  total_bill   tip  \
0       16.99  1.01  Female     No  Sun  Dinner   2.0         NaN   NaN   
1       10.34  1.66    Male     No  Sun  Dinner   3.0         NaN   NaN   
2       21.01  3.50    Male     No  Sun  Dinner   3.0         NaN   NaN   
3       23.68  3.31    Male     No  Sun  Dinner   2.0         NaN   NaN   
4         NaN   NaN     NaN    NaN  NaN     NaN   NaN       24.59  3.61   
5         NaN   NaN     NaN    NaN  NaN     NaN   NaN       25.29  4.71   
6         NaN   NaN     NaN    NaN  NaN     NaN   NaN        8.77  2.00   
7         NaN   NaN     NaN    NaN  NaN     NaN   NaN       26.88  3.12   
8         NaN   NaN     NaN    NaN  NaN     NaN   NaN       15.04  1.96   
9         NaN   NaN     NaN    NaN  NaN     NaN   NaN       14.78  3.23   

      sex smoker  day    time  size  
0     NaN    NaN  NaN     NaN   NaN  
1     NaN    NaN  NaN     NaN   NaN  
2     NaN    NaN  NaN     NaN   NaN  
3     NaN    NaN  NaN     NaN   NaN  
4  Female     No  Sun  Dinner   4.0  
5    Male     No  Sun  Dinner   4.0  
6    Male     No  Sun  Dinner   2.0  
7    Male     No  Sun  Dinner   4.0  
8    Male     No  Sun  Dinner   2.0  
9    Male     No  Sun  Dinner   2.0

In [9]:
tips_1 = tips.iloc[1]
tips_2 = tips.iloc[2]

tips_1

total_bill     10.34
tip             1.66
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 1, dtype: object

In [12]:
pd.concat([tips_1, tips_2], axis=1)

1       2
total_bill   10.34   21.01
tip           1.66     3.5
sex           Male    Male
smoker          No      No
day            Sun     Sun
time        Dinner  Dinner
size             3       3

## append

차원별로 특색 있게 바꿔준다.

In [13]:
np.append(a, 3)

array([0, 1, 2, 3, 4, 5, 3])

In [17]:
np.append(a, a) == np.concatenate((a, a))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [18]:
aa

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
np.append(aa, 3) # 2차원을 1차원으로 변환 후 append

array([0, 1, 2, 3, 4, 5, 3])

In [21]:
np.append(aa, a)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [22]:
np.append(aa, aa)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [24]:
tips_1.append(tips_2) # 없앴음(얘도 넘파이처럼 1차원으로 변환시켜줬었다.)

AttributeError: 'Series' object has no attribute 'append'

## Stack
넘파이와 판다스의 스택은 다르다.

In [25]:
np.hstack((aa, aa)) # Horizonal

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [26]:
np.vstack((aa, aa)) # Vertical

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [27]:
np.dstack((aa, aa)) # Depth, 차원 증가

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4],
        [5, 5]]])

In [33]:
aa.shape

(2, 3)

In [34]:
np.dstack((aa, aa)).shape # z축으로 차원 확장

(2, 3, 2)

In [35]:
np.dstack((aa, aa, aa)).shape

(2, 3, 3)

In [28]:
np.stack((aa, aa), axis=0) # 차원을 하나 더 높여줌

array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])

In [36]:
np.stack((aa, aa), axis=0).shape

(2, 2, 3)

In [29]:
np.stack((aa, aa), axis=1)

array([[[0, 1, 2],
        [0, 1, 2]],

       [[3, 4, 5],
        [3, 4, 5]]])

In [37]:
np.stack((aa, aa), axis=1).shape

(2, 2, 3)

In [30]:
np.stack((aa, aa), axis=2)

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4],
        [5, 5]]])

In [38]:
np.stack((aa, aa), axis=2).shape

(2, 3, 2)

In [39]:
np.column_stack((aa,aa)) # == hstack()

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [40]:
np.row_stack((aa,aa)) # == vstack()

<ipython-input-40-df75f3b71a4b>:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((aa,aa)) # == vstack()


array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [42]:
np.c_[aa, aa]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [41]:
np.r_[aa, aa]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [44]:
aaa = np.arange(24).reshape(4,6)
aaa

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [46]:
np.vsplit(aaa,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [45]:
np.vsplit(aaa,3)

ValueError: array split does not result in an equal division

In [48]:
np.vsplit(aaa,(1,2)) # 3개로 자른다

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [49]:
np.vsplit(aaa,(2,2)) # 3개로 자른다, 공집합도 나온다. 튜븦 집어넣을 수 있다

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([], shape=(0, 6), dtype=int64),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [50]:
np.hsplit(aaa,(1,2))

[array([[ 0],
        [ 6],
        [12],
        [18]]),
 array([[ 1],
        [ 7],
        [13],
        [19]]),
 array([[ 2,  3,  4,  5],
        [ 8,  9, 10, 11],
        [14, 15, 16, 17],
        [20, 21, 22, 23]])]