https://www.kaggle.com/code/ash316/eda-to-prediction-dietanic



In [1]:
import seaborn as sns

tips = sns.load_dataset('tips')

In [13]:
tips.info() # Non-Null Count

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [3]:
tips.sex # 눈에 확 들어오는 series, Record array 지원
type(tips.sex)

pandas.core.series.Series

In [4]:
# 여러 데이터를 한번에 파악하는 것이 중요하다(reduction)
tips.sex.value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [5]:
# 분석의 기본은 computation, index 기반으로 분석
tips.tip+1 # broadcasting

0      2.01
1      2.66
2      4.50
3      4.31
4      4.61
       ... 
239    6.92
240    3.00
241    3.00
242    2.75
243    4.00
Name: tip, Length: 244, dtype: float64

In [6]:
import numpy as np

x = np.ma.array([1,2,3,], mask=[True, False, False]) # 비어있는 값이 들어가는 mask array
x # 공간만 차지하고 비어있는 상태라고 치자: mask

masked_array(data=[--, 2, 3],
             mask=[ True, False, False],
       fill_value=999999)

In [11]:
x.count() # 실제 값 세준다

np.int64(2)

In [12]:
len(x) # 얘로는 missing data 검출 불가

3

In [9]:
y = np.array([None, 1, 2])
y # heterogeneous, homogeneous가 깨진다.

array([None, 1, 2], dtype=object)

In [10]:
y.count() # 기본에는 없음

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [14]:
tips.tip[0] = None # None -> NaN(비어있는 애)

<ipython-input-14-14e650885abb>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  tips.tip[0] = None
<ipython-input-14-14e650885abb>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveat

In [15]:
tips.tip[0]

np.float64(nan)

In [16]:
tips.tip[0] is None # ???

False

In [17]:
tips.tip # NaN은 마스킹 된 상태, homogeneous를 유지하기 위해

0       NaN
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [18]:
tips.tip.sum() # Pandas는 skipna 설정이 기본 옵션, scikit-learn, tf, torch는 이 옵션이 반대.

np.float64(730.5699999999999)

In [19]:
tips.tip.sum(skipna=False)

np.float64(nan)

In [20]:
tips.sex.describe()

count      244
unique       2
top       Male
freq       157
Name: sex, dtype: object

In [21]:
a = np.arange(24).reshape(4,6)

In [22]:
x = np.arange(24)

In [25]:
x.reshape(4,3,2) # shape: 원래는 괄호를 쳐야하지만, 특별히 이건 생략할게^^


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [24]:
x # inplace 없음

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
x.reshape(4,6, order='F')
# C: C언어: 가로부터
# F: Fortran: 세로부터

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [27]:
x.reshape(4,-1) # 개수는 바꾸지 않고 모양만 바꾸기, 계산하기 귀찮으면 음수로(관례상 -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [29]:
x.reshape(4,3,-1) # 음수를 두 번 할 수는 없음

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [42]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [43]:
x.resize(4,6) # 갯수를 바꾼다, return 없음, mutable 데이터
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [53]:
x.resize(3,4, refcheck=False)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
np.resize(x,(2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [49]:
np.resize(x,(3,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  0,  1,  2,  3,  4,  5]])

---

In [55]:
a = b = [1,2,3]
b.append(4)
a

[1, 2, 3, 4]

In [57]:
a = [1,2,3]
b = a
b.append(4)
a

[1, 2, 3, 4]

In [58]:
a = [1,2,3]
b = a[:] # 값을 copy
b.append(4)
a

[1, 2, 3]

In [60]:
a = [1,2,3]
b = a.copy()
b.append(4)
a

[1, 2, 3]

In [61]:
xx = [[1,2],[3,4]]
yy = xx[:]
yy = xx.copy() # shallow copy
yy[1][1] = 100
xx

[[1, 2], [3, 100]]

In [62]:
import copy

xx = [[1,2],[3,4]]
yy = copy.deepcopy(xx) # deep copy
yy[1][1] = 100
xx

[[1, 2], [3, 4]]

python
- copy : shallow copy

numpy
- copy : deep copy
- view : shallow copy

In [65]:
y = x.flatten() # copy의 개념이 들어간다

In [66]:
x[0,0] = 100
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
y.ravel() # Ravel -> Bolero -> view(shallow copy)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
import seaborn as sns

tips = sns.load_dataset('tips')
tips.tip.map(lambda x:x+1)

0      2.01
1      2.66
2      4.50
3      4.31
4      4.61
       ... 
239    6.92
240    3.00
241    3.00
242    2.75
243    4.00
Name: tip, Length: 244, dtype: float64

In [74]:
tips.sex.map(lambda x:'F' if x=='Female' else 'M')
# tips.sex.map({'Female':'F', 'Male':'M'}) # 됨

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: category
Categories (2, object): ['M', 'F']

In [75]:
# Series
tips.sex.apply(lambda x:'F' if x=='Female' else 'M')
# tips.sex.apply({'Female':'F', 'Male':'M'}) # 안됨

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: category
Categories (2, object): ['M', 'F']

In [77]:
tips.apply(lambda x:x.tip + 1, axis=1)

0      2.01
1      2.66
2      4.50
3      4.31
4      4.61
       ... 
239    6.92
240    3.00
241    3.00
242    2.75
243    4.00
Length: 244, dtype: float64

In [83]:
tips.apply(lambda x:sum(x), axis=0)
# TypeError: unsupported operand type(s) for +: 'int' and 'str'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [88]:
tips2 = tips[['total_bill', 'tip']] # 숫자 타입만 가져와서 써보자.
tips2

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [85]:
tips2.apply(lambda x:sum(x), axis=0)

total_bill    4827.77
tip            731.58
dtype: float64

In [89]:
tips2.apply(lambda x:sum(x), axis=1)

0      18.00
1      12.00
2      24.51
3      26.99
4      28.20
       ...  
239    34.95
240    29.18
241    24.67
242    19.57
243    21.78
Length: 244, dtype: float64

In [91]:
tips2.sum(axis=1)

0      18.00
1      12.00
2      24.51
3      26.99
4      28.20
       ...  
239    34.95
240    29.18
241    24.67
242    19.57
243    21.78
Length: 244, dtype: float64

In [92]:
tips2.total_bill + tips2.tip

0      18.00
1      12.00
2      24.51
3      26.99
4      28.20
       ...  
239    34.95
240    29.18
241    24.67
242    19.57
243    21.78
Length: 244, dtype: float64

add column

In [93]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [97]:
tips.groupby('sex')[['total_bill', 'tip']].mean()

<ipython-input-97-44e30d99ebb2>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby('sex')[['total_bill', 'tip']].mean()


total_bill       tip
sex                         
Male     20.744076  3.089618
Female   18.056897  2.833448

In [98]:
# 전체 식사 비용 대비 팁의 비율
tips.groupby('sex')[['total_bill', 'tip']].mean().apply(lambda x:x.tip/x.total_bill, axis=1)

<ipython-input-98-78b10120fae1>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby('sex')[['total_bill', 'tip']].mean().apply(lambda x:x.tip/x.total_bill, axis=1)


sex
Male      0.148940
Female    0.156918
dtype: float64

In [99]:
# dataframe
tips2.applymap(lambda x:x+1) # element-wise computation

<ipython-input-99-48f6bfef1108>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  tips2.applymap(lambda x:x+1)


total_bill   tip
0         17.99  2.01
1         11.34  2.66
2         22.01  4.50
3         24.68  4.31
4         25.59  4.61
..          ...   ...
239       30.03  6.92
240       28.18  3.00
241       23.67  3.00
242       18.82  2.75
243       19.78  4.00

[244 rows x 2 columns]