# [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)

## [Indexing and slicing](https://numpy.org/doc/stable/user/absolute_beginners.html#indexing-and-slicing)

별건 아니고, array 시작부분의 whitespace가 약간 거슬린다. 어떨 땐 생기고, 어떨 땐 생기지 않는다. 특별한 기준이 있을까?

In [7]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.ndim # Dimenstion

2

In [8]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [9]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [10]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [11]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


# [numpy-100](https://github.com/rougier/numpy-100)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

"10개의 삼각형을 설명하는 10개의 세쌍둥이 집합을 생각해보고, 모든 삼각형을 구성하는 고유 선분 집합을 찾아라." 라는데... **문제의 뜻을 모르겠다...**
- [np.roll](https://numpy.org/doc/stable/reference/generated/numpy.roll.html) : array를 굴리는 함수, shift 파라미터에 따라 인덱스를 설정하여 가장 앞 원소를 뒤로 보내거나 밀수 있음
- repeat : 지정한숫자 (여기선 -1)가 나오기 전까지 무한 반복

In [12]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 26) ( 0, 81) ( 6, 21) ( 6, 93) (10, 59) (10, 64) (21, 93) (24, 65)
 (24, 88) (26, 81) (28, 55) (28, 61) (30, 39) (30, 69) (31, 57) (31, 74)
 (31, 78) (31, 81) (39, 69) (43, 77) (43, 81) (55, 60) (55, 61) (55, 87)
 (57, 74) (59, 64) (60, 87) (65, 88) (77, 81) (78, 81)]
